### ISSUE TITLE
 rgeos, maptools were archived yesterday

### ISSUE THREAD

**Issue by rsbivand** [SSA-Statistical-Team-Projects/povmap#12]
@davidn10 @NoraWuerz  rgeos, maptools were archived yesterday, please remove them from povmap as soon as possible, as they are used unconditionally in in donttest settings.

**Comment by davidn10** [comment]
Thank you, Roger, for letting us know, we will work on it.

Best,
David

**Comment by davidn10** [comment]
Dear Roger,
    We have now updated the package to remove rgeos and maptools from
povmap. I apologize for the delay.
    Do you know what the procedure is to reinstate the package on CRAN?
    Thank you!

Best,
David

**Comment by rsbivand** [comment]
@davidn10 Please submit the new version online in the normal way. It will be identified as a new submission and checked more carefully than an update of a package that remained available on CRAN. So please check carefully yourself that all errors, warnings, and notes are removed (other than checking installed package size); if you can, update data to UTF-8 or explain in the submission comments why Latin-1 is needed. If you like, let me know when the code on this master branch is ready for checking, and I'll confirm your check results. CRAN also checks other aspects, so try to get the package as compliant as possible.

**Comment by davidn10** [comment]
Hi Roger,
     Thanks for your guidance so  far regarding this. We resubmitted the
package about 10 days ago. Do you have any sense of how long it will take
to review and post it on CRAN?
     Thank you!

Best,
David

**Comment by rsbivand** [comment]
@davidn10 I think you missed emails from CRAN, to which you should have responded. In https://cran.r-project.org/incoming/archive/ I see povmap_1.0.1.tar.gz, which suggests that somethoing needed resolving but to which you did not respond. Trying to run `R CMD check --as-cran` on that tar archive shows:
````
* this is package 'povmap' version '1.0.1'
* package encoding: UTF-8
* checking CRAN incoming feasibility ... [4s/16s] NOTE
Maintainer: 'Ifeanyi Edochie <iedochie@worldbank.org>'

New submission

Package was archived on CRAN

CRAN repository db overrides:
  X-CRAN-Comment: Archived on 2023-10-31 as check problems were not
    corrected in time.

Found the following (possibly) invalid URLs:
  URL: https://cran.r-project.org/web/packages/emdi/index.html
    From: README.md
    Status: 200
    Message: OK
    CRAN URL not in canonical form
  The canonical URL of the CRAN page for a package is 
    https://CRAN.R-project.org/package=pkgname
```

**Comment by rsbivand** [comment]
This is a check log for the submitted povmap, with four notes that must be addressed:
[00check.log](https://github.com/SSA-Statistical-Team-Projects/povmap/files/13394573/00check.log)

I'll try to suggest updates later today, but the main problem is the unresponsive nominated maintainer.

**Comment by rsbivand** [comment]
```
Found the following (possibly) invalid URLs:
  URL: https://cran.r-project.org/web/packages/emdi/index.html
    From: README.md
    Status: 200
    Message: OK
    CRAN URL not in canonical form
  The canonical URL of the CRAN page for a package is 
    https://CRAN.R-project.org/package=pkgname
```
`README.md` should be included in `.Rbuildignore`, it should not be included at all.

**Comment by rsbivand** [comment]
```
* checking installed package size ... NOTE
  installed size is  8.5Mb
  sub-directories of 1Mb or more:
    data      1.5Mb
    extdata   3.7Mb
    help      1.2Mb
```
The `*.dta` files can be compressed as zip archives, and unzipped if needed. This may still need to be explained on submission.

**Comment by rsbivand** [comment]
```
* checking Rd cross-references ... NOTE
Package unavailable to check Rd xrefs: ‘emdi’
```

**Comment by rsbivand** [comment]
```
* checking for detritus in the temp directory ... NOTE
Found the following files/directories:
  'RtmpQaRiye\excel_output.xlsx'
```
No files may be left when check completes. The problem is:
```
R/write.excel.emdi.R:    file <- paste0(tempdir(),"\\", "excel_output.xlsx")
```
which hardcodes a Windows file separator, should be `file <- file.path(tempdir(), "excel_output.xlsx")` to run cross-platform:
```
> paste0(tempdir(),"\\", "excel_output.xlsx")
[1] "/tmp/RtmpqcsLA4\\excel_output.xlsx"
> file.path(tempdir(), "excel_output.xlsx")
[1] "/tmp/RtmpqcsLA4/excel_output.xlsx"
```

**Comment by davidn10** [comment]
Dear Roger, I think we have now fixed these in the latest push. Would it be possible for you to check? 
Thank you very much for working with us on this! 

Best, 
David

**Comment by rsbivand** [comment]
@davidn10 Check log: 
[00check.log](https://github.com/SSA-Statistical-Team-Projects/povmap/files/13486069/00check.log)

**Comment by davidn10** [comment]
Dear Roger, thank you for your response. I think I have now addressed these remaining issues in the latest version. Would it be possible to check one more time? 
Thank you for your help! 

Best,
David

**Comment by rsbivand** [comment]
My check log using `--as-cran`: 
[00check.log](https://github.com/SSA-Statistical-Team-Projects/povmap/files/13526983/00check.log)

For the note on the README URL, add `^README\.md$` to `.Rbuildignore`. Further, you did not change line 108 in R/write.excel.emdi.R to `file.path(tempdir(), "excel_output.xlsx")`; this is required, as hard-wiring a Windows-specific file separator raises a note everywhere else https://github.com/SSA-Statistical-Team-Projects/povmap/issues/12#issuecomment-1816947310.

With these changes, new check log using `--as-cran`:
[00check.log](https://github.com/SSA-Statistical-Team-Projects/povmap/files/13527432/00check.log)

**Comment by davidn10** [comment]
Dear Roger,
    Please accept my apologies for taking this long to respond, as we were
on winter break. Thank you for your patience.
    We have now updated the repository and it passes all of the CRAN
checks. There are 0 errors, 0 warnings and 6 Notes. We arenot sure if the
Notes are problems, ut are also not sure how to fix them if they are.  The
repository is available here:
https://github.com/SSA-Statistical-Team-Projects/povmap
    Is there anything further that needs to be done to make the repository
available on CRAN?

Best regards,
David





[image: image.png]

**Comment by davidn10** [comment]
Thank you, Roger!

Best,
David
